"""Significance filter — decides which scanned files are architecturally
relevant enough to feed into the downstream agents.

The filter operates on `FileEntry` rows from the Stage-0 scan. Anything it
filters out gets `is_significant=False` (still recorded in scan.json for
completeness, so the architect can audit the filter).

Tunable thresholds (defaults configured for cloudctlplane-scale projects:
target ~50–100 entities in the final dictionary).
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from .schema import FileEntry, HpRoleHint


# ─────────────────────────────────────────────────────────────────────
# Patterns of paths that are always skipped
# ─────────────────────────────────────────────────────────────────────

_ALWAYS_SKIP_PATH_PATTERNS = [
    # Tests
    re.compile(r"(^|/)tests?/"),
    re.compile(r"(^|/)__tests__/"),
    re.compile(r"(^|/)spec/"),
    re.compile(r"_test\.[a-z]+$"),
    re.compile(r"\.test\.[a-z]+$"),
    re.compile(r"\.spec\.[a-z]+$"),
    # Build outputs / vendored
    re.compile(r"(^|/)node_modules/"),
    re.compile(r"(^|/)dist/"),
    re.compile(r"(^|/)build/"),
    re.compile(r"(^|/)target/"),         # Rust + Java
    re.compile(r"(^|/)bin/"),
    re.compile(r"(^|/)\.next/|/\.next$"),
    re.compile(r"(^|/)__pycache__/"),
    re.compile(r"\.egg-info/"),
    re.compile(r"(^|/)vendor/"),
    re.compile(r"(^|/)Pods/"),
    # Generated
    re.compile(r"(^|/)generated/"),
    re.compile(r"\.generated\.[a-z]+$"),
    re.compile(r"\.pb\.go$|_pb2\.py$|\.pb\.cc$"),
    # Docs
    re.compile(r"(^|/)docs?/"),
    re.compile(r"\.md$"),
    re.compile(r"(^|/)CHANGELOG"),
    re.compile(r"(^|/)LICENSE"),
    re.compile(r"(^|/)README"),
    # Lockfiles
    re.compile(r"(^|/)Cargo\.lock$"),
    re.compile(r"(^|/)package-lock\.json$"),
    re.compile(r"(^|/)pnpm-lock\.yaml$"),
    re.compile(r"(^|/)yarn\.lock$"),
    re.compile(r"(^|/)Pipfile\.lock$"),
    re.compile(r"(^|/)poetry\.lock$"),
    re.compile(r"(^|/)go\.sum$"),
    re.compile(r"(^|/)uv\.lock$"),
    # Images / binaries
    re.compile(r"\.(png|jpg|jpeg|gif|svg|ico|pdf|zip|tar|gz|bz2|wasm|ttf|woff2?)$"),
]


_GENERATED_CONTENT_MARKERS = [
    "DO NOT EDIT",
    "AUTO-GENERATED",
    "@generated",
    "Code generated by",
    "Auto-generated by",
]


@dataclass
class SignificanceConfig:
    """Tunable thresholds for the filter.

    Defaults aim for ~50–100 architectural entities on a cloudctlplane-scale
    project. Tighten the `min_pure_logic_lines` to shrink the dictionary;
    loosen it to capture more leaf processes."""

    min_pure_logic_lines: int = 50
    skip_config_when_size_under: int = 5   # tiny config files rarely matter
    skip_unknown_role: bool = True         # role-classifier returned None → out
    keep_all_infra: bool = True            # Stage-5 signal is precious — keep every infra file


# ─────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────

def filter_significance(
    files: Iterable[FileEntry],
    config: SignificanceConfig | None = None,
) -> list[FileEntry]:
    """Return all files annotated with `is_significant` + a `notes` reason.

    Files are not deleted — they stay in scan.json with `is_significant=False`
    so the architect can audit what got dropped."""
    cfg = config or SignificanceConfig()
    out: list[FileEntry] = []
    for f in files:
        significant, reason = _evaluate(f, cfg)
        # Preserve original notes if any; append filter reason for transparency
        notes_parts = [f.notes] if f.notes else []
        if reason:
            notes_parts.append(reason)
        out.append(
            FileEntry(
                path=f.path,
                language=f.language,
                size_lines=f.size_lines,
                hp_role_hint=f.hp_role_hint,
                is_significant=significant,
                notes=" · ".join(notes_parts) or None,
            )
        )
    return out


def is_path_always_skipped(path: str | Path) -> bool:
    """Cheap pre-walk check — used by the scanner to skip whole directory
    trees without reading files (tests/, node_modules/, etc.).

    Equivalent to evaluating the path-only skip patterns; surfaced as a
    public function so the scanner can short-circuit `os.walk`."""
    posix = Path(path).as_posix() if isinstance(path, Path) else str(path)
    return any(p.search(posix) for p in _ALWAYS_SKIP_PATH_PATTERNS)


def content_marks_generated(content: str) -> bool:
    """Return True if file content has an AUTO-GENERATED / DO NOT EDIT marker
    in the first 20 lines."""
    head = "\n".join(content.splitlines()[:20])
    return any(m in head for m in _GENERATED_CONTENT_MARKERS)


# ─────────────────────────────────────────────────────────────────────
# Internals
# ─────────────────────────────────────────────────────────────────────

def _evaluate(f: FileEntry, cfg: SignificanceConfig) -> tuple[bool, str | None]:
    """Decide significance for one file. Returns (keep, reason-for-drop-or-None)."""
    if is_path_always_skipped(f.path):
        return False, "filtered: skipped path (test / build / vendor / docs / lockfile)"

    # Role-hint-driven decisions
    hint = f.hp_role_hint
    if hint is None:
        if cfg.skip_unknown_role:
            return False, "filtered: no HP role hint classified"
        return True, None

    if hint == HpRoleHint.INFRA and cfg.keep_all_infra:
        return True, None

    if hint == HpRoleHint.CONFIG and f.size_lines < cfg.skip_config_when_size_under:
        return False, f"filtered: trivial config (< {cfg.skip_config_when_size_under} lines)"

    if hint == HpRoleHint.PURE_LOGIC and f.size_lines < cfg.min_pure_logic_lines:
        return False, f"filtered: pure-logic below threshold ({f.size_lines} < {cfg.min_pure_logic_lines} lines)"

    # boundary / state-machine / data-store and remaining config / pure-logic — keep
    return True, None
